var namespace_nuevo_proyectode_juego_1_1scripts_1_1_main_menu_1_1_sub_menus =
[
    [ "Video_settings", "class_nuevo_proyectode_juego_1_1scripts_1_1_main_menu_1_1_sub_menus_1_1_video__settings.html", "class_nuevo_proyectode_juego_1_1scripts_1_1_main_menu_1_1_sub_menus_1_1_video__settings" ],
    [ "Volumen_settings", "class_nuevo_proyectode_juego_1_1scripts_1_1_main_menu_1_1_sub_menus_1_1_volumen__settings.html", "class_nuevo_proyectode_juego_1_1scripts_1_1_main_menu_1_1_sub_menus_1_1_volumen__settings" ]
];